export const UPDATE_DATA_USER = 'UPDATE_DATA_USER';
export const UPDATE_DATA_CONTRACT = 'UPDATE_DATA_CONTRACT';
export const CREATE_CONTRACT = 'CREATE_CONTRACT';
export const CREATE_CONTRACT_SUCCESS = 'CREATE_CONTRACT_SUCCESS';
export const CREATE_TRONWEB = 'CREATE_TRONWEB';